name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    steps:
      - name: Install dependencies
        run: unset HOME; tdnf install -y build-essential git openssl-devel python3-devel sudo ca-certificates dnf sqlite-devel
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check format
        run: cargo fmt -- --check
      - name: Run cargo check
        run: cargo check --locked
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
      options: --privileged
    steps:
      - name: Install dependencies
        run: unset HOME; tdnf install -y build-essential git openssl-devel python3-devel sudo ca-certificates dnf moby-cli skopeo shadow-utils sqlite-devel
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo test
        run: cargo test --features test-docker
      - name: Setup rootless user
        run: |
          useradd -m -s /bin/bash rootless
          echo "rootless:100000:65536" > /etc/subgid
          echo "rootless:100000:65536" > /etc/subuid
      - name: Build in rootless mode
        run: |
          su - rootless
          cargo run -- build -f tests/fixtures/rootless/rpmoci.toml --image rootless --tag test

  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    steps:
      - name: Install dependencies
        run: unset HOME; tdnf install -y build-essential git openssl-devel python3-devel sudo ca-certificates dnf sqlite-devel shadow-utils 
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Make oci image
        run: make oci
